apiVersion: v1
kind: Namespace
metadata:
  name: hra2808

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpn
  namespace: hra2808
spec:
  replicas: 97
  selector:
    matchLabels:
      app: kpn
  template:
    metadata:
      labels:
        app: kpn
    spec:
      containers:
        - name: kpn
          image: marsur64/kamen_papier_noznice:december2025
          ports:
            - containerPort: 80
